# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sheng - Zhang Lin's Homepage
email: leafleafflower@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <a href="https://docs.google.com/document/d/173TM5dFUto2einRPdmwwAhWJAGpy2prtKXd705HSWZE/edit?usp=sharing">Resume</a></br>
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sheng-zhang.github.io" # the base hostname & protocol for your site
twitter_username: ShengZhangLin
github_username:  Sheng-Zhang

# Build settings
markdown: kramdown
