# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sheng - Zhang Lin's Homepage
email: leafleafflower@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  @ iOS Developer</br>
  @ Web Developer</br>
  Working History:  
  Chyiyuh Construction
  ・ BIM Coordinator at </br>
    (興富發BIM小組)</br>
  台灣林夕網路有限公司  
  ・iOS 高級工程師  
  
  </br>
  I'm Sheng-Zhang Lin, an iOS and BIM developer. I make
  some building tools to help my colleague build the model 
  more efficiently like tile tool, stair tool and ditch tool. 
  About iOS, there are 11 apps I made on app store.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sheng-zhang.github.io" # the base hostname & protocol for your site
twitter_username: leafleafflower
github_username:  Sheng-Zhang

# Build settings
markdown: kramdown
